apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: k8s-monitoring-kube-promet-prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32001
